# -*- coding: utf-8 -*-
"""practical 9 loop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15BJmCv5SZlQIxDGp4pmjRP0SiiKz4Vaa
"""

#loop---(when its required to run the block of code multiple times)
#for loop
#while loop
#for loop
list1=[1,2,3,4]
for i in list1:
  print(i)

for i in list1:
  print(2*i)

#range(5)----------0,1,2,3,4
#range(9)--------------0,1,2,3,4,5,6,7,8
for i in range(2,11):                                                       #FOR i in iterabledatatype:                                                                             #operation
  print(2*i)

fruits=['apple','banana','cherry']
for fruit in fruits:
  print(fruit)

#printing table
for i in range(1,11):
  print(f'{5} x {i} =',5*i)

tuple1=(1,2,3,4,5,6)
for i in tuple1:
  print(i*10)

city='Jaipur'
for alphabet in city:
  print(alphabet)

my_dictionary1={'name':'snigdha','city':'jaipur','pincode':302018}
for keys in my_dictionary1:
  print(keys)

for values in my_dictionary1.values():
  print(values)

for key,values in my_dictionary1.items():
  print(f"Key:{key},  Values:{values}")

#while condition:
#code to run
i=0
while i<5:
  print(i)
  i+=1

j=5
while j>0:
  print(j)
  j-=1

#even numbers b/w 2 to 10
j=2
while j<10:
  print(j)
  j+=2

#odd numbers b/w 2 to 10
j=1
while j<10:
  print(j)
  j+=2

#odd numbers b/w 10 to 0
j=9
while j>0:
  print(j)
  j-=2

#if else(conditional statements)
#if elif else
#if-----(1 condition)
#elif-----(multiple conditions)
#else--------

#if(condtion):
   #code to run
#elif(condtion):
  #code to run
#elif(condition):
  #code to run
#else:
  #code to run

x=int(input())
if x>8:
    print("x is greater")
elif x<8:
    print("x is less than 8")
else:
    print("x is equal")

a=int(input())
i=1
while i<=10:
  print(f'{a} x {i} =',a*i)
# print(a x i =a*i)
  i+=1